import {StyleSheet} from 'react-native';
const DashboardStyle = StyleSheet.create({
    view1: { flex: 1, paddingBottom: 80 },
    view2: { flex: 1, flexDirection: "row", padding: 20 },
    name1 : { fontSize: 18, color : "grey", letterSpacing: 0.5, fontWeight: "bold" },
    name2 : { paddingTop: 3, fontSize: 20, color : "#262626", letterSpacing: 0.5, fontWeight: "bold" },
    view3 : { flex: 1.5, justifyContent: "flex-end" },
    personImage : { width: "100%", height: 50, resizeMode: "cover", borderRadius : 15 },
    dotStyle : { position: "absolute", right: 0, top: -2, backgroundColor: "#ff7853", borderRadius: 10/2, width: 10, height: 10 },
    view4: { flexDirection: "row", padding: 20, paddingTop: 10 },
    searchImage: { width: 20, height: 20, resizeMode: "cover", position: "absolute", top: 15, left: 15, zIndex : 1 },
    searchJobText : { backgroundColor: "#f4f3fb", height: 50, borderWidth: 2, borderColor: "#f7f5f5", borderRadius: 20, paddingLeft: 45 },
    filterBackground : { backgroundColor: "#ff7853", width: "100%", height: 50, borderRadius: 20, justifyContent: "center", alignSelf: "center", alignItems: "center"},
    filterImage : { width: 20, height: 20, resizeMode: "cover" },
    jobText : { flexDirection: "row", padding: 20, paddingTop: 10, paddingBottom: 10 },
    view5: { flexDirection: "row", padding: 20, paddingTop: 10, paddingBottom: 10 },
    view6 : {},
    view7 : { flex: 3, paddingTop: 20, paddingLeft: 20 },
    view8 : { flexDirection: "row",  paddingTop : 25 },
    view9 : { height: 1, width: '100%', borderRadius: 1, borderWidth: 1, borderColor: '#edede8', borderStyle: 'dashed' },
    view10 : { position: 'absolute', left: 0, bottom: 0, width: '100%', height: 1, backgroundColor: 'white' },
    daysDot : { backgroundColor: "#a1a19c", borderRadius: 5/2, width: 5, height: 5 },
    day : { letterSpacing : 0.5, fontSize: 12, color: "#d1d1dc" },
    apply : { textAlign: "right", paddingRight: 15, fontWeight: "bold", letterSpacing : 0.5, fontSize: 18, color: "#6b57be" },
    applyImage : { width: 10, height: 10, resizeMode: "contain", backgroundColor: "transparent" },
    text1 : { textAlign: "center", width : 50,padding: 5, backgroundColor: "#fff4f1", color: "orange", borderRadius: 10 },
    text2 : { letterSpacing : 0.5, fontSize: 15, color: "#262626", fontWeight: "bold", paddingTop: 15 },
    text3 : { letterSpacing : 0.5, fontSize: 13, color: "#9283cf", paddingTop: 3 },
    text4 : { fontSize: 12, color: "#a8a7ad", paddingTop: 3 },
    view11 : { borderTopRightRadius: 20, borderTopLeftRadius: 20, backgroundColor:'#ffffff', elevation: 3, zIndex: 1, alignSelf: "center", justifyContent: "center" },
    view12 : { padding: 10, borderRadius: 30, backgroundColor:'#ffffff', elevation: 3, marginTop: -30 },
    view13 : { flex : 2, justifyContent: "center", alignItems: "center" }
})
module.exports = DashboardStyle;
